### ISSUE TITLE
Allow users to control candidate name variant lengths

### ISSUE THREAD

**Issue by social-virus** [bellingcat/name-variant-search#7]
Multi-part names produce a high number of candidates (see below).

Perhaps setting defaults and options for how few or many are created might help control the volume.

![image](https://github.com/bellingcat/name-variant-search/assets/127993470/e7130745-8fa6-44dc-9ff7-c73337ba4f85)

Relates to issue #2

**Comment by liliakai** [comment]
I think it's good to offer as many suggestions as possible, but there should indeed be some better organization, as suggested in #2. Especially as more types of variation are added, like alternate spellings and transliterations. I'm curious if this issue is reduced now given the latest update, which lets you make a selection of variants from the list.
